# Generated by Django 3.1.7 on 2021-03-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210312_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='training',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
