# Generated by Django 3.1.7 on 2021-03-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20210313_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='id_number',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
