# Generated by Django 3.1.7 on 2021-03-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_farmer_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='family_size',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='income',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='register_date',
        ),
    ]
