# Generated by Django 3.1.7 on 2021-03-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20210313_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropproduction',
            name='date',
            field=models.PositiveIntegerField(default=2021),
        ),
        migrations.AlterUniqueTogether(
            name='cropproduction',
            unique_together={('crop', 'farmer', 'date')},
        ),
    ]
